export const BRAND = {
  name: "소르피아97",
  tagline: "하울의 움직이는 성 실사판, 소피와 하울의 들판",
  subTagline: "경기북부 5,000평 애견동반 카페 & 캠프닉 복합공간",
  address: "경기도 동두천시 삼육사로 1802",
  area: "동두천 · 양주 · 의정부 · 남양주 · 포천",
  landmark: "동두천 놀자숲 후문 바로 앞",
  phone: "0507-1428-9515",
  phoneRaw: "050714289515",
  naverMapUrl: "https://map.naver.com/p/search/소르피아97",
  hours: "평일 12:00 ~ 22:00 · 주말 11:00 ~ 22:00 · 월요일 정기휴무",
  closedDay: "매주 월요일 휴무",
  notice: "매주 화요일은 수영장 물 교체일 · 오전 방문 시 수영장 이용 대기 가능",
  event: "🐔 강아지 닭가슴살 1개 서비스 (오픈 이벤트)",
} as const;
